# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nearby' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nearby
pod 'Kingfisher'

  target 'NearbyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NearbyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
